#pragma once

#include "stdint.h"

#define UNICAN_START_LONG_MESSAGE					0xFFFE


/*
 * Для обеспечения более лёгкой изменяемости набора команд, UNICAN_MSG_ID представлены в виде enum-ов.
 * В первой группе представлены т.н. сеттеры - коды настроек параметров двигателя.
 * 		Предполагается их использование исключительно при отладке новых двигателей.
 * Во второй группе представлены непосредственно команды.
 * 		Управление + переход в доп. режимы.
 */

enum UNICAN_ARRAY_INIT_CODE{
	UNICAN_FIRST_ARRAY_CODE = 0x0A00
};

//Сообщения - сеттеры.
enum UNICAN_SETTER_CODES
{
	UNICAN_SET_FIRST_SET_CODE = UNICAN_FIRST_ARRAY_CODE,

	UNICAN_SET_L = UNICAN_SET_FIRST_SET_CODE,
	UNICAN_SET_R,
	UNICAN_SET_J,
	UNICAN_SET_Kt,
	UNICAN_SET_Friction_static,
	UNICAN_SET_Friction_dynamic,
	UNICAN_SET_Imax,
	UNICAN_SET_Wmax,
	UNICAN_SET_Umax,

	UNICAN_SET_Q_11,
	UNICAN_SET_Q_22,
	UNICAN_SET_Q_33,
	UNICAN_SET_Q_44,
	UNICAN_SET_Q_55,
	UNICAN_SET_Q_66,
	UNICAN_SET_Q_77,

	UNICAN_SET_P_11,
	UNICAN_SET_P_22,
	UNICAN_SET_P_33,
	UNICAN_SET_P_44,
	UNICAN_SET_P_55,
	UNICAN_SET_P_66,
	UNICAN_SET_P_77,

	UNICAN_SET_R_11,
	UNICAN_SET_R_22,
	UNICAN_SET_R_33,

	UNICAN_SET_W_CONTR_DEADZONE,
	UNICAN_SET_W_CONTR_Kp,
	UNICAN_SET_W_CONTR_Ki,
	UNICAN_SET_W_CONTR_Kd,
	UNICAN_SET_W_CONTR_SatP,
	UNICAN_SET_W_CONTR_SatI,
	UNICAN_SET_W_CONTR_SatD,
	UNICAN_SET_W_CONTR_SatGen,

	UNICAN_SET_Torque_CONTR_DEADZONE,
	UNICAN_SET_Torque_CONTR_Kp,
	UNICAN_SET_Torque_CONTR_Ki,
	UNICAN_SET_Torque_CONTR_Kd,
	UNICAN_SET_Torque_CONTR_SatP,
	UNICAN_SET_Torque_CONTR_SatI,
	UNICAN_SET_Torque_CONTR_SatD,
	UNICAN_SET_Torque_CONTR_SatGen,

	UNICAN_SET_Iq_CONTR_DEADZONE,
	UNICAN_SET_Iq_CONTR_Kp,
	UNICAN_SET_Iq_CONTR_Ki,
	UNICAN_SET_Iq_CONTR_Kd,
	UNICAN_SET_Iq_CONTR_SatP,
	UNICAN_SET_Iq_CONTR_SatI,
	UNICAN_SET_Iq_CONTR_SatD,
	UNICAN_SET_Iq_CONTR_SatGen,

	UNICAN_SET_Id_CONTR_DEADZONE,
	UNICAN_SET_Id_CONTR_Kp,
	UNICAN_SET_Id_CONTR_Ki,
	UNICAN_SET_Id_CONTR_Kd,
	UNICAN_SET_Id_CONTR_SatP,
	UNICAN_SET_Id_CONTR_SatI,
	UNICAN_SET_Id_CONTR_SatD,
	UNICAN_SET_Id_CONTR_SatGen,

	UNICAN_SET_PWM_mode,
	UNICAN_SET_WINDING_TOPOLOGY,
	UNICAN_SET_NUMBER_OF_POLUS,
	UNICAN_SET_TelemetryPeriod,
	UNICAN_SET_FrictionEnable,

	UNICAN_SET_SRC_ID,
	UNICAN_SET_DEST_ID,

	UNICAN_SET_LAST_SET_CODE = UNICAN_SET_DEST_ID,
	UNICAN_SET_NUM_SET_CODES = UNICAN_SET_LAST_SET_CODE - UNICAN_SET_FIRST_SET_CODE + 1
};

//Команды.
enum UNICAN_COMMAND_CODES
{
	UNICAN_COMMAND_FIRST_COMMAND_CODE = UNICAN_SET_LAST_SET_CODE + 1,

	UNICAN_COMMAND_W_SIMPLE = UNICAN_COMMAND_FIRST_COMMAND_CODE,
	UNICAN_COMMAND_W_KALMAN,
	UNICAN_COMMAND_TORQUE_SIMPLE,
	UNICAN_COMMAND_TORQUE_KALMAN,
	UNICAN_COMMAND_CALIB_HALL,
	UNICAN_COMMAND_CALIB_CURRENT,
	UNICAN_COMMAND_APPLY_SETTINGS,
	UNICAN_COMMAND_FLASH_WRITE,
	UNICAN_COMMAND_OutputEnable,

	UNICAN_COMMAND_LAST_COMMAND_CODE = UNICAN_COMMAND_OutputEnable,
	UNICAN_COMMAND_NUM_COMMAND_CODES = UNICAN_COMMAND_LAST_COMMAND_CODE - UNICAN_COMMAND_FIRST_COMMAND_CODE + 1
};



//Коды включения соответствующей телеметрии.
enum UNICAN_ENABLER_CODES
{
	UNICAN_ENABLE_FIRST_ENABLE_CODE = UNICAN_COMMAND_LAST_COMMAND_CODE + 1,

	UNICAN_ENABLE_Id = UNICAN_ENABLE_FIRST_ENABLE_CODE,
	UNICAN_ENABLE_Iq,
	UNICAN_ENABLE_angle,

	UNICAN_ENABLE_HALL1,
	UNICAN_ENABLE_HALL2,
	UNICAN_ENABLE_HALL3,

	UNICAN_ENABLE_CURR1,
	UNICAN_ENABLE_CURR2,
	UNICAN_ENABLE_CURR3,

	UNICAN_ENABLE_W_CONTR_Perror,
	UNICAN_ENABLE_W_CONTR_Ierror,
	UNICAN_ENABLE_W_CONTR_DError,
	UNICAN_ENABLE_W_CONTR_TotError,

	UNICAN_ENABLE_Torque_CONTR_Perror,
	UNICAN_ENABLE_Torque_CONTR_Ierror,
	UNICAN_ENABLE_Torque_CONTR_DError,
	UNICAN_ENABLE_Torque_CONTR_TotError,

	UNICAN_ENABLE_Iq_CONTR_Perror,
	UNICAN_ENABLE_Iq_CONTR_Ierror,
	UNICAN_ENABLE_Iq_CONTR_DError,
	UNICAN_ENABLE_Iq_CONTR_TotError,

	UNICAN_ENABLE_Id_CONTR_Perror,
	UNICAN_ENABLE_Id_CONTR_Ierror,
	UNICAN_ENABLE_Id_CONTR_DError,
	UNICAN_ENABLE_Id_CONTR_TotError,

	UNICAN_ENABLE_Aposteriori_Id,
	UNICAN_ENABLE_Aposteriori_Iq,
	UNICAN_ENABLE_Aposteriori_angle,
	UNICAN_ENABLE_Aposteriori_W,
	UNICAN_ENABLE_Aposteriori_R,
	UNICAN_ENABLE_Aposteriori_Kf,
	UNICAN_ENABLE_Aposteriori_Tl,
	UNICAN_ENABLE_Aposteriori_Eps,
	UNICAN_ENABLE_Aposteriori_Torque,

	UNICAN_ENABLE_Ud,
	UNICAN_ENABLE_Uq,

	UNICAN_ENABLE_Voltage1_measured,

	UNICAN_ENABLE_System_time,

	UNICAN_ENABLE_LAST_ENABLE_CODE = UNICAN_ENABLE_System_time,
	UNICAN_ENABLE_NUM_ENABLE_CODES = UNICAN_ENABLE_LAST_ENABLE_CODE - UNICAN_ENABLE_FIRST_ENABLE_CODE + 1
};

//Коды телеметрии.
enum UNICAN_TELEMETRY_CODES
{
	UNICAN_TELEMETRY_FIRST_TELEMETRY_CODE = UNICAN_ENABLE_LAST_ENABLE_CODE + 1,

	UNICAN_TELEMETRY_Id = UNICAN_TELEMETRY_FIRST_TELEMETRY_CODE,
	UNICAN_TELEMETRY_Iq,
	UNICAN_TELEMETRY_angle,

	UNICAN_TELEMETRY_HALL1,
	UNICAN_TELEMETRY_HALL2,
	UNICAN_TELEMETRY_HALL3,

	UNICAN_TELEMETRY_CURR1,
	UNICAN_TELEMETRY_CURR2,
	UNICAN_TELEMETRY_CURR3,

	UNICAN_TELEMETRY_W_CONTR_Perror,
	UNICAN_TELEMETRY_W_CONTR_Ierror,
	UNICAN_TELEMETRY_W_CONTR_DError,
	UNICAN_TELEMETRY_W_CONTR_TotError,

	UNICAN_TELEMETRY_Torque_CONTR_Perror,
	UNICAN_TELEMETRY_Torque_CONTR_Ierror,
	UNICAN_TELEMETRY_Torque_CONTR_DError,
	UNICAN_TELEMETRY_Torque_CONTR_TotError,

	UNICAN_TELEMETRY_Iq_CONTR_Perror,
	UNICAN_TELEMETRY_Iq_CONTR_Ierror,
	UNICAN_TELEMETRY_Iq_CONTR_DError,
	UNICAN_TELEMETRY_Iq_CONTR_TotError,

	UNICAN_TELEMETRY_Id_CONTR_Perror,
	UNICAN_TELEMETRY_Id_CONTR_Ierror,
	UNICAN_TELEMETRY_Id_CONTR_DError,
	UNICAN_TELEMETRY_Id_CONTR_TotError,

	UNICAN_TELEMETRY_Aposteriori_Id,
	UNICAN_TELEMETRY_Aposteriori_Iq,
	UNICAN_TELEMETRY_Aposteriori_angle,
	UNICAN_TELEMETRY_Aposteriori_W,
	UNICAN_TELEMETRY_Aposteriori_R,
	UNICAN_TELEMETRY_Aposteriori_Kf,
	UNICAN_TELEMETRY_Aposteriori_Tl,
	UNICAN_TELEMETRY_Aposteriori_Eps,
	UNICAN_TELEMETRY_Aposteriori_Torque,

	UNICAN_TELEMETRY_Ud,
	UNICAN_TELEMETRY_Uq,

	UNICAN_TELEMETRY_Voltage1_measured,

	UNICAN_TELEMETRY_System_time,

	UNICAN_TELEMETRY_LAST_TELEMETRY_CODE = UNICAN_TELEMETRY_System_time,
	UNICAN_TELEMETRY_NUM_TELEMETRY_CODES = UNICAN_TELEMETRY_LAST_TELEMETRY_CODE - UNICAN_TELEMETRY_FIRST_TELEMETRY_CODE + 1
};

enum UNICAN_ARRAY_FINI_CODE{
	UNICAN_LAST_ARRAY_CODE = UNICAN_TELEMETRY_LAST_TELEMETRY_CODE,
	UNICAN_NUM_ARRAY_CODES = UNICAN_LAST_ARRAY_CODE - UNICAN_FIRST_ARRAY_CODE + 1
};
