#ifndef UNICAN_MESSAGE_ID_H_
#define UNICAN_MESSAGE_ID_H_

#define AVS_TELEMETRY_X 0x0B10
#define AVS_TELEMETRY_Y 0x0B11
#define AVS_TELEMETRY_Z 0x0B12

#define UNICAN_START_LONG_MESSAGE 0xFFFE

#endif /* UNICAN_MESSAGE_ID_H_ */
